#include "GoxApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<GoxApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

GoxApp::GoxApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  GoxApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  GoxApp::associateSyntax(_syntax, _action_factory);
}

GoxApp::~GoxApp()
{
}

// External entry point for dynamic application loading
extern "C" void GoxApp__registerApps() { GoxApp::registerApps(); }
void
GoxApp::registerApps()
{
  registerApp(GoxApp);
}

// External entry point for dynamic object registration
extern "C" void GoxApp__registerObjects(Factory & factory) { GoxApp::registerObjects(factory); }
void
GoxApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void GoxApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { GoxApp::associateSyntax(syntax, action_factory); }
void
GoxApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
